name: coffee_api
description: A Very Good Project created by Very Good CLI.
version: 0.2.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
