import 'dart:typed_data';

import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart';

part 'coffee.g.dart';

/// {@template coffee}
/// A cached coffee object.
/// {@endtemplate}
@HiveType(typeId: 0)
class Coffee extends Equatable {
  /// {@macro coffee}
  const Coffee({
    required this.bytes,
    this.url,
  });

  /// The url used to fetch this [Coffee] image
  @HiveField(0)
  final String? url;

  /// The bytes generated by this [Coffee] image
  @HiveField(1)
  final Uint8List bytes;

  @override
  List<Object?> get props => [url, bytes];
}
