import 'dart:typed_data';

import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart';

part 'favorite_coffee.g.dart';

/// {@template coffee}
/// A favorite coffee object.
/// {@endtemplate}
@HiveType(typeId: 0)
class FavoriteCoffee extends Equatable {
  /// {@macro coffee}
  const FavoriteCoffee({
    required this.bytes,
    this.url,
  });

  /// The url used to fetch this [FavoriteCoffee] image
  @HiveField(0)
  final String? url;

  /// The bytes generated by this [FavoriteCoffee] image
  @HiveField(1)
  final Uint8List bytes;

  @override
  List<Object?> get props => [bytes, url];
}
