name: key_value_storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive: ^2.2.3
  meta: ^1.8.0
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
