name: coffee_repository
description: A Very Good Project created by Very Good CLI.
version: 0.2.2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  coffee_api:
    path: ../coffee_api
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  key_value_storage:
    path: ../key_value_storage
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
